version: '3'

services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
  redis-admin:
    image: rediscommander/redis-commander
    ports:
      - 4568:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
